name: 'docker-deploy'

description: 'Build push and deploy Docker image'
inputs:
  COMPOSE-PATH:
    description: 'Path to the docker-compose file'
    required: true
  HOST:
    description: 'Hostname of vps'
    required: true
  PORT:
    description: 'ssh port of vps'
    required: true
  USERNAME:
    description: 'ssh username of vps'
    required: true
  KEY:
    description: 'ssh key of vps'
    required: true
  PASSPHRASE:
    description: 'passphrase of ssh key of vps'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub token for GitHub packages'
    required: true

runs:
  using: 'composite'
  steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ inputs.GITHUB_TOKEN }}

      - name: Prepare metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          build-args: |
            APP_RELEASE=${{ github.sha }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy the new image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ inputs.HOST }}
          port: ${{ inputs.PORT }}
          username: ${{ inputs.USERNAME }}
          key: ${{ inputs.KEY }}
          passphrase: ${{ inputs.PASSPHRASE }}
          script: |
            cd ${{ inputs.COMPOSE-PATH }}
            docker compose down
            docker rmi ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            docker compose up -d
